---
# global settings
pid_dir: '~/.pg_chameleon/pid/'
log_dir: '~/.pg_chameleon/logs/'
log_dest: file
log_level: info
log_days_keep: 10
rollbar_key: ''
rollbar_env: ''

# type_override allows the user to override the default type conversion
# into a different one.

type_override:
  "tinyint(1)":
    override_to: boolean
    override_tables:
      - "*"


# postgres  destination connection
pg_conn:
  host: "postgres"
  port: "5432"
  user: "user"
  password: "123456"
  database: "testdb"
  charset: "utf8"

sources:
  mysql:
    db_conn:
      host: "mysql"
      port: "3306"
      user: "root"
      password: "123456"
      charset: 'utf8'
      connect_timeout: 10
    schema_mappings:
      testdb: public
    limit_tables:
      - testdb.t_test
    skip_tables: []
    grant_select_to:
      - usr_readonly
    lock_timeout: "120s"
    my_server_id: 1
    replica_batch_size: 10000
    replay_max_rows: 10000
    batch_retention: '1 day'
    copy_max_memory: "300M"
    copy_mode: 'file'
    out_dir: /tmp
    sleep_loop: 1
    on_error_replay: continue
    on_error_read: continue
    auto_maintenance: "disabled"
    gtid_enable: false
    type: mysql
    skip_events:
      insert: [] # skips inserts on delphis_mediterranea.foo
      delete: []# skips deletes on schema delphis_mediterranea
      update:
    keep_existing_schema: No
